<?php

declare(strict_types=1);

use App\Configuration\ClubSettings;
use App\Http\Controllers\Auth\InvitationController;
use App\Http\Controllers\Bookings\BookingController;
use App\Http\Controllers\Calendar\CalendarController;
use App\Http\Controllers\Calendar\CalendarEventController;
use App\Http\Controllers\Calendar\CalendarFeedController;
use App\Http\Controllers\Calendar\CalendarReportController;
use App\Http\Controllers\CommunicationController;
use App\Http\Controllers\Configuration\BackupController;
use App\Http\Controllers\Configuration\ClubController;
use App\Http\Controllers\Configuration\ClubLogoController;
use App\Http\Controllers\Configuration\DonationSettingsController;
use App\Http\Controllers\Configuration\FinanceSettingsController;
use App\Http\Controllers\Configuration\MailSettingsController;
use App\Http\Controllers\Configuration\MemberFieldController;
use App\Http\Controllers\Configuration\PublicPageSettingsController;
use App\Http\Controllers\Configuration\SecurityAuditController;
use App\Http\Controllers\Configuration\SelfServiceSettingsController;
use App\Http\Controllers\Configuration\SoftwareModuleController;
use App\Http\Controllers\Configuration\SystemController;
use App\Http\Controllers\Configuration\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DemoMailboxController;
use App\Http\Controllers\Donations\DonationController;
use App\Http\Controllers\Finance\FinanceBankImportController;
use App\Http\Controllers\Finance\FinanceInvoiceController;
use App\Http\Controllers\Finance\FinanceReturnDebitController;
use App\Http\Controllers\Finance\FinanceSepaExportController;
use App\Http\Controllers\Forms\FinanceMandateController;
use App\Http\Controllers\Forms\ReceiptController;
use App\Http\Controllers\Forms\SignatureListController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\Inventory\InventoryController;
use App\Http\Controllers\Inventory\InventoryDocumentController;
use App\Http\Controllers\Inventory\InventorySheetController;
use App\Http\Controllers\Members\AssignmentOverviewController;
use App\Http\Controllers\Members\BulkAssignMemberController;
use App\Http\Controllers\Members\BulkUpdateMemberController;
use App\Http\Controllers\Members\MemberAssignmentController;
use App\Http\Controllers\Members\MemberCardController;
use App\Http\Controllers\Members\MemberController;
use App\Http\Controllers\Members\MemberExportController;
use App\Http\Controllers\Members\MemberImportController;
use App\Http\Controllers\Members\MemberIndexController;
use App\Http\Controllers\Members\MembershipApplicationController;
use App\Http\Controllers\Members\MembershipCancellationController;
use App\Http\Controllers\Members\PostalCodeController;
use App\Http\Controllers\Members\WelcomeMailController;
use App\Http\Controllers\Payments\BankImportController;
use App\Http\Controllers\Payments\ContributionController;
use App\Http\Controllers\Payments\DunningController;
use App\Http\Controllers\Payments\InvoiceController;
use App\Http\Controllers\Payments\MandateExportController;
use App\Http\Controllers\Payments\ManualPaymentController;
use App\Http\Controllers\Payments\PaymentController;
use App\Http\Controllers\Payments\ReturnDebitController;
use App\Http\Controllers\Payments\SepaExportController;
use App\Http\Controllers\Payments\TransactionExportController;
use App\Http\Controllers\Payments\TransactionReceiptController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\Security\AuditLogController;
use App\Http\Controllers\SelfService\AccessController;
use App\Http\Controllers\SelfService\BookingController as SelfServiceBookingController;
use App\Http\Controllers\SelfService\CancellationController as SelfServiceCancellationController;
use App\Http\Controllers\SelfService\DocumentController as SelfServiceDocumentController;
use App\Http\Controllers\SelfService\FormController as SelfServiceFormController;
use App\Http\Controllers\SelfService\PasskeyController as SelfServicePasskeyController;
use App\Http\Controllers\SelfService\PortalController;
use App\Http\Controllers\SelfService\ProfileController as SelfServiceProfileController;
use App\Http\Controllers\SelfService\TransactionReceiptController as SelfServiceTransactionReceiptController;
use App\Http\Controllers\StatisticsController;
use App\Http\Middleware\EnsureSelfService;
use App\Http\Middleware\RequireAllowedSelfServiceEmail;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('install', [InstallController::class, 'create'])->name('install.create');
Route::post('install', [InstallController::class, 'store'])->middleware('throttle:5,1')->name('install.store');

Route::get('/', fn (ClubSettings $settings) => Inertia::render('Welcome', ['selfserviceEnabled' => $settings->enabled('selfservice_enabled'), 'publicJoinEnabled' => $settings->enabled('public_join_enabled')]))->name('home');
Route::get('branding/logo', [ClubLogoController::class, 'show'])->name('branding.logo');
Route::get('impressum', [PublicPageController::class, 'imprint'])->name('imprint');
Route::get('datenschutz', [PublicPageController::class, 'privacy'])->name('privacy');
Route::middleware('throttle:60,1')->prefix('demo/postfach')->group(function () {
    Route::get('/', [DemoMailboxController::class, 'index'])->name('demo.mailbox.index');
    Route::get('{mail}/html', [DemoMailboxController::class, 'html'])->whereNumber('mail')->name('demo.mailbox.html');
    Route::get('{mail}/anhang/{index}', [DemoMailboxController::class, 'attachment'])->whereNumber(['mail', 'index'])->name('demo.mailbox.attachment');
});
Route::get('kalender/abo/{token}.ics', [CalendarFeedController::class, 'publicFeed'])->middleware(['module:calendar', 'throttle:60,1'])->name('calendar.feed.public');
Route::get('kalender/mein-abo/{token}.ics', [CalendarFeedController::class, 'memberFeed'])->middleware(['module:calendar', 'throttle:60,1'])->name('calendar.feed.member');
Route::get('sepa-mandat/{token}', [FinanceMandateController::class, 'publicShow'])->where('token', '[A-Za-z0-9]{64}')->middleware('throttle:60,1')->name('forms.mandates.sign');
Route::post('sepa-mandat/{token}', [FinanceMandateController::class, 'publicSign'])->where('token', '[A-Za-z0-9]{64}')->middleware('throttle:10,1')->name('forms.mandates.sign.store');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::inertia('ueber-gymslunity', 'About')->name('about');
    Route::middleware(['module:communication', 'can:view-communication'])->prefix('kommunikation')->group(function () {
        Route::get('/', [CommunicationController::class, 'index'])->defaults('tab', 'mail')->name('kommunikation');
        Route::get('serienmails', [CommunicationController::class, 'index'])->defaults('tab', 'mail')->name('communication.mail');
        Route::get('serienbriefe', [CommunicationController::class, 'index'])->defaults('tab', 'letters')->name('communication.letters');
        Route::get('verlauf', [CommunicationController::class, 'index'])->defaults('tab', 'history')->name('communication.history');
        Route::get('verlauf/{campaign}/bericht.pdf', [CommunicationController::class, 'report'])->whereNumber('campaign')->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('communication.report');
        Route::post('serienmails', [CommunicationController::class, 'sendMail'])->middleware('throttle:2,1')->name('communication.mail.send');
        Route::post('serienbriefe', [CommunicationController::class, 'generateLetters'])->middleware(['throttle:10,1', 'reconfirm', 'audit:data_export'])->name('communication.letters.generate');
    });
    Route::middleware(['module:payments', 'can:view-payments'])->prefix('beitraege')->group(function () {
        Route::get('/', PaymentController::class)->defaults('tab', 'overview')->name('payments');
        Route::get('mandate', PaymentController::class)->defaults('tab', 'mandates')->name('payments.mandates.index');
        Route::get('anlegen', PaymentController::class)->defaults('tab', 'create')->name('payments.create');
        Route::get('rechnungen', PaymentController::class)->defaults('tab', 'invoices')->name('payments.invoices.index');
        Route::get('mahnwesen', PaymentController::class)->defaults('tab', 'dunning')->name('payments.dunning.index');
        Route::get('sepa-export', PaymentController::class)->defaults('tab', 'sepa')->name('payments.sepa.index');
        Route::get('bankimport', PaymentController::class)->defaults('tab', 'bank')->name('payments.bank-import.index');
        Route::get('ruecklastschriften', PaymentController::class)->defaults('tab', 'returns')->name('payments.return-debits.index');
        Route::get('manuell-buchen', PaymentController::class)->defaults('tab', 'manual')->name('payments.manual.index');
        Route::post('anlegen', [ContributionController::class, 'store'])->name('payments.contributions.store');
        Route::get('kontobuchungen/{transaction}/beleg.pdf', TransactionReceiptController::class)->whereNumber('transaction')->middleware(['throttle:sensitive', 'audit:document_access'])->name('payments.transactions.receipt');
        Route::get('mandate/export', MandateExportController::class)->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.mandates.export');
        Route::get('kontobuchungen/export', TransactionExportController::class)->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.transactions.export');
        Route::post('rechnungen/erzeugen', [InvoiceController::class, 'generate'])->name('payments.invoices.generate');
        Route::post('rechnungen/versenden', [InvoiceController::class, 'send'])->name('payments.invoices.send');
        Route::post('rechnungen/sammeldownload', [InvoiceController::class, 'combined'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.invoices.combined');
        Route::get('rechnungen/{contribution}', [InvoiceController::class, 'document'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('payments.invoices.document');
        Route::get('mahnwesen/export', [DunningController::class, 'export'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.dunning.export');
        Route::get('mahnwesen/tabelle', [DunningController::class, 'table'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.dunning.table');
        Route::post('mahnwesen/briefe', [DunningController::class, 'letters'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.dunning.letters');
        Route::post('mahnwesen/versenden', [DunningController::class, 'send'])->middleware('throttle:2,1')->name('payments.dunning.send');
        Route::get('mahnwesen/{member:member_number}', [DunningController::class, 'document'])->whereNumber('member')->middleware(['throttle:sensitive', 'audit:document_access'])->name('payments.dunning.document');
        Route::post('sepa-export', SepaExportController::class)->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('payments.sepa.export');
        Route::post('bankimport', BankImportController::class)->name('payments.bank-import');
        Route::post('bankimport/{paymentImport}/zeilen/{row}/zuordnen', [BankImportController::class, 'assign'])->name('payments.bank-import.assign');
        Route::post('bankimport/{paymentImport}/zeilen/{row}/ignorieren', [BankImportController::class, 'ignore'])->name('payments.bank-import.ignore');
        Route::post('ruecklastschriften', ReturnDebitController::class)->name('payments.return-debits.store');
        Route::post('manuell-buchen', ManualPaymentController::class)->name('payments.manual.store');
    });
    Route::middleware(['module:statistics', 'can:view-statistics'])->prefix('auswertungen')->group(function () {
        Route::get('/', [StatisticsController::class, 'index'])->defaults('tab', 'overview')->name('statistics');
        Route::get('mitglieder', [StatisticsController::class, 'index'])->defaults('tab', 'members')->name('statistics.members');
        Route::get('finanzen', [StatisticsController::class, 'index'])->defaults('tab', 'finances')->name('statistics.finances');
        Route::get('datenqualitaet', [StatisticsController::class, 'index'])->defaults('tab', 'quality')->name('statistics.quality');
        Route::get('bericht.pdf', [StatisticsController::class, 'pdf'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('statistics.pdf');
        Route::get('bestandsmeldung.csv', [StatisticsController::class, 'stockCsv'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('statistics.stock-csv');
    });
    Route::middleware(['module:finance', 'can:view-finance'])->prefix('buchhaltung')->group(function () {
        Route::inertia('/', 'finance/Overview')->name('finance');
        Route::get('rechnungen', [FinanceInvoiceController::class, 'index'])->name('finance.invoices.index');
        Route::get('rechnungen/rechnungsbuch.pdf', [FinanceInvoiceController::class, 'report'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('finance.invoices.report');
        Route::get('rechnungen/anlegen', [FinanceInvoiceController::class, 'create'])->name('finance.invoices.create');
        Route::post('rechnungen', [FinanceInvoiceController::class, 'store'])->name('finance.invoices.store');
        Route::get('rechnungen/sepa-export', [FinanceSepaExportController::class, 'index'])->name('finance.invoices.sepa.index');
        Route::post('rechnungen/sepa-export', [FinanceSepaExportController::class, 'export'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('finance.invoices.sepa.export');
        Route::post('rechnungen/sepa-export/{uuid}/rueckgaengig', [FinanceSepaExportController::class, 'reverse'])->whereUuid('uuid')->name('finance.invoices.sepa.reverse');
        Route::get('rechnungen/bankimport', [FinanceBankImportController::class, 'index'])->name('finance.invoices.bank-import.index');
        Route::post('rechnungen/bankimport', [FinanceBankImportController::class, 'import'])->name('finance.invoices.bank-import.store');
        Route::post('rechnungen/bankimport/{import}/zeilen/{row}/zuordnen', [FinanceBankImportController::class, 'assign'])->name('finance.invoices.bank-import.assign');
        Route::post('rechnungen/bankimport/{import}/zeilen/{row}/ignorieren', [FinanceBankImportController::class, 'ignore'])->name('finance.invoices.bank-import.ignore');
        Route::get('rechnungen/ruecklastschriften', [FinanceReturnDebitController::class, 'index'])->name('finance.invoices.return-debits.index');
        Route::post('rechnungen/ruecklastschriften/{row}', [FinanceReturnDebitController::class, 'store'])->name('finance.invoices.return-debits.store');
        Route::get('rechnungen/{invoice}/{format}', [FinanceInvoiceController::class, 'document'])->whereIn('format', ['pdf', 'xrechnung'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('finance.invoices.document');
        Route::post('rechnungen/{invoice}/versenden', [FinanceInvoiceController::class, 'send'])->middleware('throttle:5,1')->name('finance.invoices.send');
        Route::patch('rechnungen/{invoice}/bezahlt', [FinanceInvoiceController::class, 'markPaid'])->name('finance.invoices.paid');
        Route::patch('rechnungen/{invoice}/erstattet', [FinanceInvoiceController::class, 'refund'])->name('finance.invoices.refunded');
        Route::post('rechnungen/{invoice}/stornieren', [FinanceInvoiceController::class, 'cancel'])->name('finance.invoices.cancel');
    });
    Route::inertia('formulare', 'Forms')->middleware(['module:forms', 'can:view-forms'])->name('forms');
    Route::middleware(['module:forms', 'can:view-forms'])->prefix('formulare/quittungen')->name('receipts.')->group(function () {
        Route::get('/', [ReceiptController::class, 'index'])->defaults('tab', 'list')->name('index');
        Route::get('anlegen', [ReceiptController::class, 'index'])->defaults('tab', 'create')->name('create');
        Route::get('archiv', [ReceiptController::class, 'index'])->defaults('tab', 'list')->name('archive');
        Route::get('quittungsbuch.pdf', [ReceiptController::class, 'report'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('report');
        Route::post('/', [ReceiptController::class, 'store'])->middleware('throttle:10,1')->name('store');
        Route::get('{receipt}', [ReceiptController::class, 'show'])->name('show');
        Route::get('{receipt}/pdf/{edition}', [ReceiptController::class, 'document'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('document');
        Route::post('{receipt}/versenden', [ReceiptController::class, 'send'])->middleware('throttle:5,1')->name('send');
        Route::post('{receipt}/stornieren', [ReceiptController::class, 'cancel'])->name('cancel');
    });
    Route::middleware(['module:forms', 'can:view-forms'])->prefix('formulare/unterschriftslisten')->name('forms.signature-lists.')->group(function () {
        Route::get('/', [SignatureListController::class, 'index'])->name('index');
        Route::post('pdf', [SignatureListController::class, 'document'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('document');
    });
    Route::middleware(['module:forms', 'can:view-forms'])->prefix('formulare/sepa-mandate')->name('forms.mandates.')->group(function () {
        Route::get('/', [FinanceMandateController::class, 'index'])->defaults('tab', 'overview')->name('index');
        Route::get('anlegen', [FinanceMandateController::class, 'index'])->defaults('tab', 'create')->name('create');
        Route::get('mandatsbuch.pdf', [FinanceMandateController::class, 'report'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('report');
        Route::post('/', [FinanceMandateController::class, 'store'])->middleware('throttle:10,1')->name('store');
        Route::get('{mandate}/pdf', [FinanceMandateController::class, 'document'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('document');
        Route::post('{mandate}/versenden', [FinanceMandateController::class, 'send'])->middleware('throttle:5,1')->name('send');
        Route::post('{mandate}/unterschrieben', [FinanceMandateController::class, 'markSigned'])->name('signed');
        Route::post('{mandate}/widerrufen', [FinanceMandateController::class, 'revoke'])->name('revoke');
    });
    Route::middleware(['module:donations', 'can:view-donations'])->prefix('spenden')->group(function () {
        Route::get('/', [DonationController::class, 'index'])->defaults('tab', 'ledger')->name('donations');
        Route::get('anlegen', [DonationController::class, 'index'])->defaults('tab', 'create')->name('donations.create');
        Route::get('offene-bestaetigungen', [DonationController::class, 'index'])->defaults('tab', 'open')->name('donations.open');
        Route::get('spendenbuch.pdf', [DonationController::class, 'report'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('donations.report');
        Route::post('/', [DonationController::class, 'store'])->name('donations.store');
        Route::post('{donation}/ausstellen', [DonationController::class, 'issue'])->name('donations.certificates.issue');
        Route::get('bestaetigungen/{certificate}', [DonationController::class, 'document'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('donations.certificates.document');
        Route::post('bestaetigungen/{certificate}/versenden', [DonationController::class, 'send'])->name('donations.certificates.send');
        Route::post('bestaetigungen/{certificate}/widerrufen', [DonationController::class, 'revoke'])->name('donations.certificates.revoke');
    });
    Route::middleware(['module:inventory', 'can:view-inventory'])->prefix('inventar')->group(function () {
        Route::get('/', [InventoryController::class, 'index'])->defaults('tab', 'overview')->name('inventory');
        Route::get('inventarisieren', [InventoryController::class, 'index'])->defaults('tab', 'create')->name('inventory.create');
        Route::post('/', [InventoryController::class, 'store'])->name('inventory.store');
        Route::get('inventarliste.pdf', [InventoryController::class, 'report'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('inventory.report');
        Route::get('{inventoryItem:inventory_number}', [InventoryController::class, 'show'])->name('inventory.show');
        Route::get('{inventoryItem:inventory_number}/bearbeiten', [InventoryController::class, 'edit'])->name('inventory.edit');
        Route::patch('{inventoryItem:inventory_number}', [InventoryController::class, 'update'])->name('inventory.update');
        Route::patch('{inventoryItem:inventory_number}/abgang', [InventoryController::class, 'dispose'])->name('inventory.dispose');
        Route::get('{inventoryItem:inventory_number}/inventarblatt.pdf', InventorySheetController::class)->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('inventory.sheet');
        Route::post('{inventoryItem:inventory_number}/belege', [InventoryDocumentController::class, 'store'])->name('inventory.documents.store');
        Route::get('{inventoryItem:inventory_number}/belege/{inventoryDocument}', [InventoryDocumentController::class, 'show'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('inventory.documents.show');
    });
    Route::middleware(['module:calendar', 'can:view-calendar'])->prefix('kalender')->name('calendar.')->group(function () {
        Route::get('/', [CalendarController::class, 'index'])->name('index');
        Route::get('terminliste.pdf', CalendarReportController::class)->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('report');
        Route::post('/', [CalendarController::class, 'store'])->name('store');
        Route::patch('{calendar}', [CalendarController::class, 'update'])->name('update');
        Route::delete('{calendar}', [CalendarController::class, 'destroy'])->name('destroy');
        Route::put('{calendar}/freigaben', [CalendarController::class, 'updateRules'])->name('rules.update');
        Route::post('{calendar}/abo-link', [CalendarController::class, 'enablePublicLink'])->name('public-link.store');
        Route::delete('{calendar}/abo-link', [CalendarController::class, 'disablePublicLink'])->name('public-link.destroy');
        Route::post('termine', [CalendarEventController::class, 'store'])->name('events.store');
        Route::patch('termine/{event}', [CalendarEventController::class, 'update'])->name('events.update');
        Route::delete('termine/{event}', [CalendarEventController::class, 'destroy'])->name('events.destroy');
    });
    Route::middleware(['module:bookings', 'can:view-bookings'])->prefix('buchungen')->name('bookings.')->group(function () {
        Route::get('/', [BookingController::class, 'index'])->defaults('tab', 'calendar')->name('index');
        Route::get('ressourcen', [BookingController::class, 'index'])->defaults('tab', 'resources')->name('resources.index');
        Route::get('ressourcen/anlegen', [BookingController::class, 'index'])->defaults('tab', 'resource-create')->name('resources.create');
        Route::get('anfragen', [BookingController::class, 'index'])->defaults('tab', 'requests')->name('requests.index');
        Route::get('anlegen', [BookingController::class, 'index'])->defaults('tab', 'create')->name('create');
        Route::get('ressourcen/{resource}', [BookingController::class, 'show'])->name('resources.show');
        Route::post('ressourcen', [BookingController::class, 'storeResource'])->name('resources.store');
        Route::patch('ressourcen/{resource}', [BookingController::class, 'updateResource'])->name('resources.update');
        Route::post('/', [BookingController::class, 'store'])->name('store');
        Route::patch('{booking}/entscheidung', [BookingController::class, 'decide'])->name('decide');
        Route::get('{booking}', [BookingController::class, 'showBooking'])->name('booking.show');
        Route::patch('{booking}', [BookingController::class, 'updateBooking'])->name('booking.update');
        Route::patch('{booking}/stornieren', [BookingController::class, 'cancel'])->name('cancel');
    });
    Route::get('ortsangaben', PostalCodeController::class)->middleware('throttle:60,1')->name('postal.lookup');
    Route::get('mitglieder', MemberIndexController::class)->name('members.index');
    Route::get('mitglieder/antraege', [MembershipApplicationController::class, 'index'])->name('members.applications.index');
    Route::post('mitglieder/{member:member_number}/beitritt-freigeben', [MembershipApplicationController::class, 'approve'])->name('members.applications.approve');
    Route::get('mitglieder/kuendigungen', [MembershipCancellationController::class, 'index'])->name('members.cancellations.index');
    Route::patch('mitglieder/{member:member_number}/kuendigung-bestaetigen', [MembershipCancellationController::class, 'confirm'])->name('members.cancellations.confirm');
    Route::get('mitglieder/anlegen', [MemberController::class, 'create'])->name('members.create');
    Route::post('mitglieder/anlegen', [MemberController::class, 'store'])->name('members.store');
    Route::get('mitglieder/importieren', [MemberImportController::class, 'index'])->name('members.import.index');
    Route::get('mitglieder/importieren/vorlage', [MemberImportController::class, 'template'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('members.import.template');
    Route::post('mitglieder/importieren/vorschau', [MemberImportController::class, 'preview'])->name('members.import.preview');
    Route::post('mitglieder/importieren/zuordnen', [MemberImportController::class, 'map'])->name('members.import.map');
    Route::post('mitglieder/importieren/abschliessen', [MemberImportController::class, 'store'])->name('members.import.store');
    Route::post('mitglieder/export', MemberExportController::class)->middleware(['throttle:20,1', 'reconfirm', 'audit:data_export'])->name('members.export');
    Route::patch('mitglieder/massenbearbeitung', BulkUpdateMemberController::class)->middleware('throttle:10,1')->name('members.bulk-update');
    Route::post('mitglieder/massenzuordnung', BulkAssignMemberController::class)->middleware(['can:manage-assignments', 'throttle:10,1'])->name('members.bulk-assign');
    Route::post('mitglieder/willkommensmail', WelcomeMailController::class)->middleware('throttle:10,1')->name('members.welcome-mail');
    Route::get('mitglieder/{member:member_number}/karteiblatt', MemberCardController::class)->middleware(['throttle:sensitive', 'audit:document_access'])->name('members.card');
    Route::get('mitglieder/{member:member_number}', [MemberController::class, 'show'])->middleware('audit:member_viewed')->name('members.show');
    Route::patch('mitglieder/{member:member_number}', [MemberController::class, 'update'])->name('members.update');
    Route::middleware('can:view-assignments')->group(function () {
        $export = ['throttle:sensitive', 'reconfirm', 'audit:data_export'];
        Route::get('aemter', [AssignmentOverviewController::class, 'offices'])->defaults('tab', 'current')->name('assignments.offices');
        Route::get('aemter/verlauf', [AssignmentOverviewController::class, 'offices'])->defaults('tab', 'history')->name('assignments.offices.history');
        Route::get('aemter/stichtag', [AssignmentOverviewController::class, 'offices'])->defaults('tab', 'date')->name('assignments.offices.date');
        Route::get('aemter/export', [AssignmentOverviewController::class, 'exportOffices'])->middleware($export)->name('assignments.offices.export');
        Route::get('abteilungen', [AssignmentOverviewController::class, 'departments'])->name('assignments.departments');
        Route::get('abteilungen/export', [AssignmentOverviewController::class, 'exportDepartments'])->middleware($export)->name('assignments.departments.export');
        Route::get('ehrungen', [AssignmentOverviewController::class, 'honors'])->defaults('tab', 'list')->name('assignments.honors');
        Route::get('ehrungen/jubilaeen', [AssignmentOverviewController::class, 'honors'])->defaults('tab', 'jubilees')->name('assignments.honors.jubilees');
        Route::get('ehrungen/export', [AssignmentOverviewController::class, 'exportHonors'])->middleware($export)->name('assignments.honors.export');
    });
    Route::post('mitglieder/{member:member_number}/zuordnungen', [MemberAssignmentController::class, 'store'])->middleware('can:manage-assignments')->name('members.assignments.store');
    Route::patch('mitglieder/{member:member_number}/zuordnungen/{assignment}', [MemberAssignmentController::class, 'update'])->whereNumber('assignment')->middleware('can:manage-assignments')->name('members.assignments.update');
    Route::patch('mitglieder/{member:member_number}/zuordnungen/{assignment}/beenden', [MemberAssignmentController::class, 'end'])->whereNumber('assignment')->middleware('can:manage-assignments')->name('members.assignments.end');
    Route::patch('mitglieder/{member:member_number}/zuordnungen/{assignment}/wechseln', [MemberAssignmentController::class, 'switch'])->whereNumber('assignment')->middleware('can:manage-assignments')->name('members.assignments.switch');
    Route::delete('mitglieder/{member:member_number}/zuordnungen/{assignment}', [MemberAssignmentController::class, 'destroy'])->whereNumber('assignment')->middleware('can:manage-assignments')->name('members.assignments.destroy');
    Route::post('mitglieder/{member:member_number}/dokumente/{kind}', [MemberController::class, 'storeDocument'])->name('members.documents.store');
    Route::get('mitglieder/{member:member_number}/dokumente/{kind}', [MemberController::class, 'document'])->middleware(['throttle:sensitive', 'audit:document_access'])->name('members.document');
    Route::get('mitglieder/{member:member_number}/mandate/{document}', [MemberController::class, 'mandateDocument'])->whereNumber('document')->middleware(['throttle:sensitive', 'audit:document_access'])->name('members.mandates.document');
    Route::middleware('can:manage-configuration')->prefix('konfiguration')->name('configuration.')->group(function () {
        Route::redirect('/', '/konfiguration/verein');
        Route::get('verein', [ClubController::class, 'edit'])->name('club.edit');
        Route::patch('verein', [ClubController::class, 'update'])->name('club.update');
        Route::post('verein/logo', [ClubLogoController::class, 'store'])->name('club.logo.store');
        Route::delete('verein/logo', [ClubLogoController::class, 'destroy'])->name('club.logo.destroy');
        Route::get('mitgliedsfelder', [MemberFieldController::class, 'index'])->name('fields.index');
        Route::post('mitgliedsfelder', [MemberFieldController::class, 'store'])->name('fields.store');
        Route::patch('mitgliedsfelder/reihenfolge', [MemberFieldController::class, 'reorder'])->name('fields.reorder');
        Route::patch('mitgliedsfelder/{field}', [MemberFieldController::class, 'update'])->name('fields.update');
        Route::get('benutzer', [UserController::class, 'index'])->name('users.index');
        Route::post('benutzer', [UserController::class, 'store'])->middleware('reconfirm')->name('users.store');
        Route::patch('benutzer/{user}', [UserController::class, 'update'])->middleware('reconfirm')->name('users.update');
        Route::post('benutzer/{user}/einladung', [UserController::class, 'invite'])->middleware(['throttle:5,1', 'reconfirm'])->name('users.invite');
        Route::get('email', [MailSettingsController::class, 'edit'])->name('mail.edit');
        Route::patch('email', [MailSettingsController::class, 'update'])->middleware('reconfirm')->name('mail.update');
        Route::post('email/test', [MailSettingsController::class, 'test'])->middleware(['throttle:5,1', 'reconfirm'])->name('mail.test');
        Route::get('selfservice', [SelfServiceSettingsController::class, 'edit'])->name('selfservice.edit');
        Route::patch('selfservice', [SelfServiceSettingsController::class, 'update'])->name('selfservice.update');
        Route::get('startseite', [PublicPageSettingsController::class, 'edit'])->name('public-pages.edit');
        Route::patch('startseite', [PublicPageSettingsController::class, 'update'])->name('public-pages.update');
        Route::get('softwaremodule', [SoftwareModuleController::class, 'edit'])->name('modules.edit');
        Route::patch('softwaremodule', [SoftwareModuleController::class, 'update'])->name('modules.update');
        Route::get('spenden', [DonationSettingsController::class, 'edit'])->name('donations.edit');
        Route::patch('spenden', [DonationSettingsController::class, 'update'])->name('donations.update');
        Route::get('buchhaltung', [FinanceSettingsController::class, 'edit'])->name('finance.edit');
        Route::patch('buchhaltung', [FinanceSettingsController::class, 'update'])->name('finance.update');
        Route::get('system', SystemController::class)->name('system');
        Route::post('system/updates', [SystemController::class, 'checkForUpdates'])->middleware('throttle:5,1')->name('system.updates');
        Route::get('system/backup/konfiguration', [BackupController::class, 'downloadConfiguration'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:configuration_backup_export'])->name('backup.configuration.download');
        Route::get('system/backup/datenbank', [BackupController::class, 'downloadDatabase'])->middleware(['throttle:2,1', 'reconfirm', 'audit:database_backup_export'])->name('backup.database.download');
        Route::post('system/backup/konfiguration', [BackupController::class, 'restoreConfiguration'])->middleware(['throttle:5,1', 'reconfirm', 'audit:configuration_backup_restore'])->name('backup.configuration.restore');
        Route::post('system/backup/datenbank', [BackupController::class, 'restoreDatabase'])->middleware(['throttle:2,1', 'reconfirm', 'audit:database_backup_restore'])->name('backup.database.restore');
        Route::get('sicherheitsprotokoll', SecurityAuditController::class)->name('security-audit');
    });
});

require __DIR__.'/settings.php';

Route::middleware('guest')->group(function () {
    Route::get('einladung/{token}', [InvitationController::class, 'show'])->middleware('throttle:20,1')->name('invitation.show');
    Route::post('einladung', [InvitationController::class, 'store'])->middleware('throttle:10,1')->name('invitation.store');
});

Route::middleware(['auth', 'verified', 'can:view-audit'])->prefix('auditlog')->group(function () {
    Route::get('/', [AuditLogController::class, 'index'])->name('audit.index');
    Route::get('export', [AuditLogController::class, 'export'])->middleware(['throttle:sensitive', 'reconfirm', 'audit:data_export'])->name('audit.export');
});
Route::middleware(EnsureSelfService::class)->prefix('selfservice')->group(function () {
    Route::get('zugang', [AccessController::class, 'index']);
    Route::get('mitglied-werden', [AccessController::class, 'join']);
    Route::post('zugang/anfordern', [AccessController::class, 'request'])->middleware('throttle:10,1');
    Route::post('zugang/bestaetigen', [AccessController::class, 'consume'])->middleware('throttle:10,1');
    Route::get('email/bestaetigen/{token}', [AccessController::class, 'confirmEmail'])
        ->where('token', '[a-f0-9]{64}')
        ->middleware('throttle:10,1')
        ->name('selfservice.email.confirm');
    Route::post('abmelden', [AccessController::class, 'logout']);
    Route::get('passkey-anmeldung/optionen', [SelfServicePasskeyController::class, 'loginOptions'])->middleware('throttle:30,1')->name('selfservice.passkeys.login-options');
    Route::post('passkey-anmeldung', [SelfServicePasskeyController::class, 'login'])->middleware('throttle:10,1')->name('selfservice.passkeys.login');
    Route::get('/', PortalController::class);
    // Locked while the stored address violates the e-mail filter.
    Route::middleware(RequireAllowedSelfServiceEmail::class)->group(function () {
        Route::get('passkeys/optionen', [SelfServicePasskeyController::class, 'registrationOptions'])->middleware('throttle:10,1')->name('selfservice.passkeys.options');
        Route::post('passkeys', [SelfServicePasskeyController::class, 'store'])->middleware('throttle:10,1')->name('selfservice.passkeys.store');
        Route::delete('passkeys/{memberPasskey}', [SelfServicePasskeyController::class, 'destroy'])->whereNumber('memberPasskey')->middleware('throttle:10,1')->name('selfservice.passkeys.destroy');
        Route::post('kalender-link/erneuern', [PortalController::class, 'renewCalendarLink'])->middleware('throttle:5,1')->name('selfservice.calendar-link.renew');
        Route::patch('profil', [SelfServiceProfileController::class, 'update'])->middleware('throttle:20,1');
        Route::patch('mitgliedschaft/kuendigen', [SelfServiceCancellationController::class, 'store'])->middleware('throttle:5,1');
        Route::delete('mitgliedschaft/kuendigen', [SelfServiceCancellationController::class, 'destroy'])->middleware('throttle:5,1');
        Route::get('beitritt', [SelfServiceFormController::class, 'show'])->defaults('kind', 'application');
        Route::get('mandat', [SelfServiceFormController::class, 'show'])->defaults('kind', 'sepa');
        Route::post('formulare/application', [SelfServiceFormController::class, 'storeApplication'])->middleware('throttle:5,1');
        Route::post('formulare/sepa', [SelfServiceFormController::class, 'storeMandate'])->middleware('throttle:5,1');
        Route::get('dokumente/{kind}', SelfServiceDocumentController::class)->middleware(['throttle:30,1', 'audit:document_access']);
        Route::get('kontobuchungen/{transaction}/beleg.pdf', SelfServiceTransactionReceiptController::class)->whereNumber('transaction')->middleware(['module:payments', 'throttle:30,1', 'audit:document_access'])->name('selfservice.transactions.receipt');
        Route::middleware('module:bookings')->group(function () {
            Route::get('buchungen', [SelfServiceBookingController::class, 'index'])->name('selfservice.bookings.index');
            Route::post('buchungen', [SelfServiceBookingController::class, 'store'])->middleware('throttle:10,1')->name('selfservice.bookings.store');
            Route::delete('buchungen/{booking}', [SelfServiceBookingController::class, 'cancel'])->middleware('throttle:10,1')->name('selfservice.bookings.cancel');
        });
    });
});
