<!doctype html><html lang="de"><head><meta charset="utf-8"><style>
@page { margin: 22px 30px; } body { font-family: DejaVu Sans, sans-serif; font-size: 9px; line-height: 1.4; color: #18232d; } h1 { font-size: 23px; margin: 0; } h2 { font-size: 15px; } table { width: 100%; border-collapse: collapse; table-layout: fixed; } td { vertical-align: top; padding: 5px 8px; overflow-wrap: break-word; } .header td { padding: 0 0 10px; } .label { font-size: 8px; color: #546372; } .data td { border: 1px solid #cbd5e1; } .value { white-space: pre-wrap; } .signature { height: 52px; max-width: 210px; } .logo { max-width: 110px; max-height: 50px; } footer { font-size: 7px; margin-top: 10px; color: #546372; } .notes { page-break-before: always; } .block { page-break-inside: avoid; }
</style></head><body>
<table class="header"><tr><td>@if($logo)<img class="logo" src="{{ $logo }}">@endif</td><td><h1>Quittung</h1><strong>{{ $edition === 'original' ? 'Original für den Zahlungsgeber' : 'Kopie für den Zahlungsempfänger' }}</strong></td><td style="text-align:right">{{ $receipt['club']['name'] ?? '' }}<br>{{ $receipt['club']['street'] ?? '' }}<br>{{ $receipt['club']['postal_code'] ?? '' }} {{ $receipt['club']['city'] ?? '' }}<br>{{ $receipt['club']['email'] ?? '' }}</td></tr></table>
<table class="data"><tr><td><div class="label">Quittungsnummer</div>{{ $receipt['receipt_number'] }}</td><td><div class="label">Datum</div>{{ \Carbon\CarbonImmutable::parse($receipt['receipt_date'])->format('d.m.Y') }}</td><td><div class="label">Betrag (brutto)</div><strong>{{ number_format($receipt['amount_cents']/100, 2, ',', '.') }} {{ $receipt['currency'] }}</strong></td></tr>
<tr><td><div class="label">Nettobetrag</div>{{ number_format($receipt['net_cents']/100, 2, ',', '.') }} {{ $receipt['currency'] }}</td><td><div class="label">Umsatzsteuer {{ $receipt['vat_rate'] }} %</div>{{ number_format($receipt['vat_cents']/100, 2, ',', '.') }} {{ $receipt['currency'] }}</td><td><div class="label">Grund für 0 % / ermäßigten Satz</div>{{ $receipt['vat_reason'] ?? '—' }}</td></tr>
<tr><td colspan="3"><div class="label">Betrag in Worten</div>{{ $receipt['amount_words'] }}</td></tr></table>
<table class="data"><tr><td><div class="label">Zahlung von (Zahlungsgeber)</div><div class="value">{{ $receipt['payer'] }}</div></td><td><div class="label">Zahlung an (Zahlungsempfänger)</div><div class="value">{{ $receipt['payee'] }}</div></td></tr><tr><td colspan="2"><div class="label">Für / Zahlungsgrund</div><div class="value">{{ $receipt['purpose'] }}</div></td></tr></table>
<div class="block"><table><tr><td><strong>Betrag erhalten</strong><br>{{ $receipt['signer_name'] }}<br><span class="label">Name Zahlungsempfänger / unterschreibende Person</span></td><td>@if($signature)<img class="signature" src="{{ $signature }}"><br><span class="label">Unterschrift Zahlungsempfänger</span>@else<strong>Digital unterzeichnet</strong><br><span class="label">Authentifiziertes Benutzerkonto · {{ $receipt['created_by_name'] }} · {{ $receipt['created_at'] }}</span>@endif</td></tr></table></div>
<footer>Erstellt am {{ $receipt['created_at'] }} · Benutzer: {{ $receipt['created_by_name'] }} · IP: {{ $receipt['ip'] }}<br>Die Hinweise auf der Folgeseite gehören zu dieser Quittung.</footer>
<div class="notes"><h1>Hinweise zur Quittung</h1><h2>{{ $receipt['receipt_number'] }} · {{ $edition === 'original' ? 'Original' : 'Kopie' }}</h2><div class="value">{{ $receipt['notes'] }}</div><p>Die Angaben zu Betrag, Zahlung und Umsatzsteuer wurden bei Ausstellung festgehalten. Das gespeicherte Dokument wird bei späteren Änderungen der Vereinsdaten nicht verändert.</p></div>
</body></html>
