<!DOCTYPE html><html lang="de"><head><meta charset="utf-8"><style>
@page { margin: 36px 45px; } body { font-family: DejaVu Sans, sans-serif; font-size: 10px; line-height: 1.45; color: #17212b; } header { font-size: 9px; } .header td { border: 0; padding: 0; } .header .club { text-align: right; } .logo { max-width: 160px; max-height: 64px; } h1 { font-size: 23px; margin: 24px 0; } h2 { font-size: 13px; } .text { white-space: pre-wrap; margin: 18px 0; } table { width: 100%; border-collapse: collapse; } td { border-bottom: 1px solid #ddd; padding: 6px; vertical-align: top; } .signature { height: 75px; max-width: 270px; } .block { page-break-inside: avoid; } footer { margin-top: 20px; font-size: 8px; color: #555; }
</style></head><body>
<header><table class="header"><tr><td>@if($logo)<img class="logo" src="{{ $logo }}" alt="Vereinslogo">@endif</td><td class="club"><strong>{{ $club['name'] ?? '' }}</strong><br>{{ $club['street'] ?? '' }}<br>{{ $club['postal_code'] ?? '' }} {{ $club['city'] ?? '' }}<br>{{ $club['email'] ?? '' }}<br>{{ $club['register_number'] ?? '' }} · {{ $club['register_court'] ?? '' }}</td></tr></table></header>
<h1>{{ $kind === 'application' ? 'Mitgliedsantrag' : 'SEPA-Lastschriftmandat' }}</h1>
<table><tr><td>Mitgliedsnummer</td><td>{{ $member->member_number }}</td></tr><tr><td>Name</td><td>{{ $member->first_name }} {{ $member->middle_name }} {{ $member->last_name }}</td></tr>
<tr><td>Geburtsdatum / Geschlecht</td><td>{{ $member->birth_date?->format('d.m.Y') }} · {{ ['m' => 'Männlich', 'w' => 'Weiblich', 'd' => 'Divers', 'o' => 'Ohne Angabe'][$member->gender] ?? 'Keine Angabe' }}</td></tr><tr><td>Adresse</td><td>{{ $member->street }}, {{ $member->postal_code }} {{ $member->city }}, {{ $member->country }}</td></tr><tr><td>Kontakt</td><td>{{ $member->email }} · {{ $member->mobile_phone }}</td></tr>
@if($kind === 'application')<tr><td>Mitgliedschaft</td><td>{{ $application?->membership_type ?? $member->membership_type }}@if($member->sponsor_contribution) · Förderbetrag {{ number_format((float) $member->sponsor_contribution, 2, ',', '.') }} €@endif · {{ $application ? 'Antrag wartet auf Freigabe; noch kein Eintrittsdatum' : 'Eintritt '.$member->joined_at?->format('d.m.Y') }}</td></tr>@else
<tr><td>IBAN</td><td>{{ \App\Support\Iban::format($member->iban) }}</td></tr><tr><td>Mandatsreferenz</td><td>{{ $member->mandate_reference }}</td></tr><tr><td>Gläubiger-ID</td><td>{{ $club['creditor_id'] ?? '' }}</td></tr><tr><td>Kontoinhaber</td><td>{{ $member->account_holder_first_name }} {{ $member->account_holder_last_name }}<br>{{ $member->account_holder_street }}<br>{{ $member->account_holder_postal_code }} {{ $member->account_holder_city }}, {{ $member->account_holder_country }}</td></tr>@endif</table>
<div class="text">{{ $texts[$kind === 'application' ? 'application_text' : 'sepa_text'] }}</div>
<div class="block"><img class="signature" src="{{ $signature }}"><div>{{ $kind === 'application' ? 'Unterschrift Mitglied' : 'Unterschrift Kontoinhaber' }}</div></div>
@if($guardian)<div class="block"><div class="text">{{ $texts['guardian_text'] }}</div><img class="signature" src="{{ $guardian }}"><div>Unterschrift Sorgeberechtigte: {{ $guardianName }}</div></div>@endif
<footer>Digital abgegeben und ausdrücklich bestätigt am {{ $timestamp }} · IP-Adresse: {{ $ip }}<br>Dieses PDF dokumentiert die zum Zeitpunkt der Abgabe bestätigten Angaben und Formulartexte.</footer>
</body></html>
